const T={
 en:{language:'Language',home:'Home',tools:'Toolkit',how:'How it works',sovereignty:'Data sovereignty',join:'Join us',review:'Translations are working drafts. Te reo Māori and Chinese wording must be reviewed with fluent speakers and Māori partners before a pilot.',more:'More community languages will be prioritised with pilot partners.',save:'Save choices on this device',saved:'Your choices were saved on this device only.',receipt:'Create consent receipt',clear:'Clear demo data',cleared:'Demo data cleared.',start:'Start timer',calculate:'Calculate',weeks:'weeks without gambling could retain',localOnly:'This demonstration stores preferences only in this browser. It sends nothing to BannedBand or any third party.'},
 mi:{language:'Reo',home:'Kāinga',tools:'Kete taputapu',how:'Te āhua o te mahi',sovereignty:'Rangatiratanga raraunga',join:'Hono mai',review:'He tauira mahi ēnei whakamāoritanga. Me arotake ngā kupu reo Māori me ngā hoa Māori i mua i tētahi whakamātautau.',more:'Ka whakaraupapatia ētahi atu reo ā-hapori me ngā hoa whakamātautau.',save:'Tiakina ngā kōwhiringa ki tēnei pūrere',saved:'Kua tiakina ō kōwhiringa ki tēnei pūrere anake.',receipt:'Waihangatia he rīhiti whakaaetanga',clear:'Mukua ngā raraunga tauira',cleared:'Kua mukua ngā raraunga tauira.',start:'Tīmatahia te wā',calculate:'Tātaihia',weeks:'wiki kāore e petipeti ana, ka puritia pea',localOnly:'Ka tiakina ngā manakohanga o tēnei tauira ki tēnei pūtirotiro anake. Kāore he raraunga e tukuna ki BannedBand, ki tētahi atu rānei.'},
 'zh-Hans':{language:'语言',home:'首页',tools:'工具',how:'运作方式',sovereignty:'数据主权',join:'加入我们',review:'翻译目前为工作草稿。试点前，毛利语和中文内容必须由流利使用者及毛利合作伙伴审核。',more:'其他社区语言将与试点合作伙伴共同确定优先顺序。',save:'在此设备上保存选择',saved:'您的选择仅保存在此设备上。',receipt:'生成同意记录',clear:'清除演示数据',cleared:'演示数据已清除。',start:'开始计时',calculate:'计算',weeks:'周不赌博，可能节省',localOnly:'此演示仅在当前浏览器中保存偏好，不会向 BannedBand 或任何第三方发送数据。'},
 'zh-Hant':{language:'語言',home:'首頁',tools:'工具',how:'運作方式',sovereignty:'資料主權',join:'加入我們',review:'翻譯目前為工作草稿。試點前，毛利語及中文內容必須由流利使用者和毛利合作夥伴審核。',more:'其他社區語言將與試點合作夥伴共同確定優先次序。',save:'在此裝置儲存選擇',saved:'您的選擇只儲存在此裝置。',receipt:'建立同意紀錄',clear:'清除示範資料',cleared:'示範資料已清除。',start:'開始計時',calculate:'計算',weeks:'週不賭博，可能節省',localOnly:'此示範只在目前瀏覽器中儲存偏好，不會向 BannedBand 或任何第三方傳送資料。'}
};
const labels={en:'English',mi:'te reo Māori','zh-Hans':'简体中文','zh-Hant':'繁體中文'};
function currentLang(){return localStorage.getItem('bb-language')||((navigator.language||'').startsWith('mi')?'mi':(navigator.language||'').startsWith('zh')?'zh-Hans':'en')}
function header(){const page=document.body.dataset.page||'';document.body.insertAdjacentHTML('afterbegin',`<a class="skip" href="#main">Skip to content</a><header class="site-header"><div class="header-inner"><a class="brand" href="index.html">BannedBand</a><nav class="nav" aria-label="Main navigation"><a data-t="home" href="index.html" ${page==='home'?'aria-current="page"':''}></a><a data-t="tools" href="toolkit.html" ${page==='tools'?'aria-current="page"':''}></a><a data-t="how" href="system.html" ${page==='system'?'aria-current="page"':''}></a><a data-t="sovereignty" href="sovereignty.html" ${page==='sovereignty'?'aria-current="page"':''}></a><a data-t="join" href="join.html" ${page==='join'?'aria-current="page"':''}></a></nav><div class="language"><label data-t="language" for="language"></label><select id="language" aria-label="Language">${Object.entries(labels).map(([v,n])=>`<option value="${v}">${n}</option>`).join('')}</select></div></div></header><div class="translation-note" data-t="review"></div>`)}
function footer(){document.body.insertAdjacentHTML('beforeend',`<footer class="footer"><div class="footer-inner"><strong>BannedBand / Xclusion Systems International Limited</strong><p data-t="more"></p><div class="lang-roadmap" aria-label="Languages being considered"><span class="pill">Gagana Samoa</span><span class="pill">lea faka-Tonga</span><span class="pill">Hindi</span><span class="pill">NZ Sign Language</span></div><p class="small">© 2026 · <a href="sovereignty.html">Data commitments</a></p></div></footer>`)}
function apply(lang){const d=T[lang]||T.en;document.documentElement.lang=lang==='mi'?'mi':lang.startsWith('zh')?lang:'en';document.querySelectorAll('[data-t]').forEach(el=>{const k=el.dataset.t;if(d[k])el.textContent=d[k]});document.getElementById('language').value=lang;localStorage.setItem('bb-language',lang);document.dispatchEvent(new CustomEvent('languagechange',{detail:{lang}}))}
document.addEventListener('DOMContentLoaded',()=>{header();footer();const l=currentLang();apply(l);document.getElementById('language').addEventListener('change',e=>apply(e.target.value))});
window.BBi18n={T,currentLang,apply};